src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("top.urls")),
    path('accounts/', include("accounts.urls")),
    path('gentext/', include("gentext.urls")),
    path('corpus/', include("corpus.urls")),
]

src/gentext/urls.py
from django.urls import path
from . import views

app_name = 'gentext'
urlpatterns = [
	path('', views.index, name='index'),
	path('generate/', views.generate, name='generate'),
	path('generate_all/', views.generate_all, name='generate_all'),
	path('select/', views.select, name='select'),
	path('result_all/', views.result_all, name='result_all'),
]

src/gentext/models.py
from django.db import models
from django.conf import settings

#############################################################################
# 日記
#############################################################################
class Diary(models.Model):
	user		= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	name		= models.CharField(max_length=16, verbose_name='日記名', default='My Diary')
	created_at	= models.DateTimeField(auto_now_add=True)
	updated_at	= models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = '日記'

#############################################################################
# 日記の各ページ用
#############################################################################
class DiaryPage(models.Model):
	diary		= models.ForeignKey(Diary, on_delete=models.CASCADE)
	date		= models.DateTimeField(verbose_name='日付')
	keyword		= models.CharField(max_length=62, verbose_name='キーワード')
	body		= models.TextField(verbose_name='本文')
	img_path	= models.CharField(max_length=256, verbose_name='画像パス', default='')
	favorite	= models.BooleanField(verbose_name='お気に入り', default=False)
	is_public	= models.BooleanField(verbose_name='公開フラグ', default=False)
	created_at	= models.DateTimeField(auto_now_add=True)
	updated_at	= models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.body

	class Meta:
		verbose_name_plural = '日記ページ'

#############################################################################
# 日記の設定用
#############################################################################
class DiaryConfig(models.Model):
	diary		= models.ForeignKey(Diary, on_delete=models.CASCADE)
	main_color	= models.CharField(max_length=6, verbose_name='メインカラー', default='00AFCC')
	sub_color	= models.CharField(max_length=6, verbose_name="サブカラー", default='4169E1')

src/gentext/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django_celery_results.models import TaskResult
from django.template import loader
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from app.tasks import gentext, gentext_all
from urllib import parse
import re, os, datetime
from logging import getLogger
from .models import Diary, DiaryPage

#############################################################################
# 日記生成のトップ画面
#############################################################################
@login_required
def index(request):
    params = {}

    # 日記を取得、あるいは新規作成
    diary, create = Diary.objects.get_or_create(user=request.user)
    diary_pages = DiaryPage.objects.filter(diary=diary.id).order_by('date')
    params['pages'] = diary_pages

    # セッションの値をクリア
    request.session['task_id'] = ''
    request.session['input_text'] = ''
    request.session['date_first'] = ''
    request.session['result_list'] = ''

    return render(request, 'gentext/index.html', params)

#############################################################################
# 日記追加画面
#############################################################################
@login_required
def generate(request):
    params = {}

    # セッションの値をクリア
    request.session['task_id'] = ''
    request.session['input_text'] = ''
    return render(request, 'gentext/generate.html', params)

#############################################################################
# 文章の生成と選択画面
#############################################################################
@login_required
def select(request):
    params = {}

    # 送信ボタンが押されたら非同期で実行
    if 'btn_send' in request.POST and request.session['task_id'] == '':

        date = request.POST['diary_date']
        if len(date) < 1:
            messages.error(request, '日記の日付を指定してください。')
            return redirect('gentext:generate')

        # 入力文章を取得
        input_text = request.POST['input_text']
        if len(input_text) < 1:
            messages.error(request, 'キーワードを入力してください。')
            return redirect('gentext:generate')

        type = request.POST['type']
        if not type in ['place', 'event']:
            messages.error(request, '文章タイプの指定が不正です。')
            return redirect('gentext:generat')

        # 非同期実行
        task_id = gentext.delay(input_text, type)
        # 値をセッションで保持
        request.session['input_text'] = input_text
        request.session['date'] = date
        request.session['task_id'] = str(task_id)

    # 結果を取得
    results = TaskResult.objects.all()

    # 結果が取得できるまでは待機
    if len(results) == 0:
        params['results'] = 'wait'
        return render(request, 'gentext/select.html', params)

    # セッションで保持したtask_idをもとに結果を取得
    if results[0].task_id == request.session['task_id']:
        # 表示文字列の成形
        molded_results = list(results.values_list('result', flat=True))[0]
        # 不要な文字をトリム
        molded_results = re.sub(r'\[|\]|\"', '', molded_results)
        # 文字列をカンマで分割してリスト化
        molded_results = molded_results.split(',', 1)

        # 結果を分割取得
        illustration_file = '/static/img/illustration/' + molded_results[0]
        texts = molded_results[1]
        # 文字列のデコード
        texts = texts.encode().decode('unicode-escape')
        # 文字列をカンマで分割してリスト化
        texts = texts.split(',')

        params['results'] = texts
        params['illustration_file'] = illustration_file
    else:
        params['results'] = 'wait'


    # 決定ボタンが押されたら
    if 'btn_decide' in request.POST:
        diary = Diary.objects.get(user=request.user)

        diary_page = DiaryPage()
        diary_page.diary = diary
        diary_page.date = request.session['date']
        diary_page.keyword = request.session['input_text']
        diary_page.body = request.POST['text']
        diary_page.img_path = request.POST['image']
        diary_page.save()

        # セッションクリア
        request.session['task_id'] = ''
        request.session['input_text'] = ''
        request.session['date'] = ''

        messages.info(request, '日記を作成しました。')
        return redirect('gentext:index')

    return render(request, 'gentext/select.html', params)

#############################################################################
# 一気に作る
#############################################################################
@login_required
def generate_all(request):
    params = {}

    # セッションの値をクリア
    request.session['task_id'] = ''
    request.session['date_first'] = ''
    request.session['result_list'] = ''
    return render(request, 'gentext/generate_all.html', params)

#############################################################################
# 一気に作る
#############################################################################
@login_required
def result_all(request):
    params = {}

    # 送信ボタンが押されたら非同期で実行
    if 'btn_send' in request.POST and request.session['task_id'] == '':

        date_first = None
        days = 0

        # 入力情報を取得
        if request.POST['mode'] == 'range':
            date_from = request.POST['diary_date_from']
            if len(date_from) < 1:
                messages.error(request, '日記の期間を指定してください。')
                return redirect('gentext:generate_all')
            date_to = request.POST['diary_date_to']
            if len(date_to) < 1:
                messages.error(request, '日記の期間を指定してください。')
                return redirect('gentext:generate_all')

            date_first = date_from
            days = datetime.datetime.strptime(date_to, '%Y-%m-%d') - datetime.datetime.strptime(date_from, '%Y-%m-%d')
            days = days.days + 1
            if days < 1:
                messages.error(request, '日記の期間の指定が不正です。')
                return redirect('gentext:generate_all')

        elif request.POST['mode'] == 'span':
            date = request.POST['diary_date']
            if len(date) < 1:
                messages.error(request, '日記の開始日を指定してください。')
                return redirect('gentext:generate_all')
            span = request.POST['span']
            if span == 'day':
                days = 1
            elif span == 'week':
                days = 7
            elif span == 'month':
                days = 30
            else:
                messages.error(request, '日数の指定が不正です。')
                return redirect('gentext:generat_all')

            date_first = date

        # 非同期実行
        task_id = gentext_all.delay(days)
        # 値をセッションで保持
        request.session['date_first'] = date_first
        request.session['task_id'] = str(task_id)

    # 結果を取得
    results = TaskResult.objects.all()

    # 結果が取得できるまでは待機
    if len(results) == 0:
        params['results'] = 'wait'
        return render(request, 'gentext/result_all.html', params)

    # セッションで保持したtask_idをもとに結果を取得
    if results[0].task_id == request.session['task_id']:
        # 表示文字列の成形
        molded_results = list(results.values_list('result', flat=True))[0]
        # 不要な文字をトリム
        molded_results = re.sub(r'\[|\]|\"', '', molded_results)
        # 文字列をカンマで分割してリスト化
        molded_results = molded_results.split(',')

        # 結果を分割取得
        illustration_files = molded_results[0::2]
        texts = []
        for data in molded_results[1::2]:
            # 文字列のデコード
            texts.append(data.encode().decode('unicode-escape'))

        date_list = []
        result_list = []
        for i, text in enumerate(texts):
            date = datetime.datetime.strptime(request.session['date_first'], '%Y-%m-%d') + datetime.timedelta(days=i)
            result_list.append({
                'date': str(date),
                'text': text,
            })

        params['results'] = result_list
        request.session['result_list'] = result_list
        request.session['file_list'] = illustration_files
    else:
        params['results'] = 'wait'


    # 次へボタンが押されたら
    if 'btn_next' in request.POST:
        data_list = request.session['result_list']
        file_list = request.session['file_list']
        for data, file in zip(data_list, file_list):
            diary = Diary.objects.get(user=request.user)

            if file.strip() == 'none' or file.strip() == 'None':
                file = 'default.png'

            diary_page = DiaryPage()
            diary_page.diary = diary
            diary_page.date = data['date']
            diary_page.keyword = ''
            diary_page.body = data['text']
            diary_page.img_path = '/static/img/illustration/' + file.strip()
            diary_page.save()

        # セッションクリア
        request.session['task_id'] = ''
        request.session['result_list'] = ''
        request.session['date_first'] = ''

        messages.info(request, '日記を保存しました。')
        return redirect('gentext:index')

    return render(request, 'gentext/result_all.html', params)

src/templates/gentext/generate.html
{% extends "_common/base.html" %}
{% block sub_title %}TOP{% endblock %}

{% block main %}

<div class="gentext-generate text-center">

  <div class="ui-heading">
    <h2>文章を生成します</h2>
  </div>

  <div class="mb-4">
    <div class="flex-fill">
      <form class="ui-form bg-white shadow rounded-3 p-5" method="POST" action="{% url 'gentext:select' %}">
        {% csrf_token %}
        <div class="form-floating mb-4">
          <input class="form-control date-picker" type="text" name="diary_date" placeholder="date">
          <label>日記の日付</label>
        </div>
        <div class="form-floating mb-4">
          <input class="form-control" type="text" name="input_text" placeholder="keyword">
          <label>キーワード</label>
        </div>
        <select name="type" class="form-select mb-4" aria-label="Default select">
          <option value="none" selected>文章タイプを選択してください</option>
          <option value="place">行った場所</option>
          <option value="event">やったこと</option>
        </select>

        <div class="mt-1 d-flex justify-content-center">
          <a class="btn btn-secondary mx-1" href="{% url 'gentext:index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace" viewBox="0 0 16 16">
              <path d="M5.83 5.146a.5.5 0 0 0 0 .708L7.975 8l-2.147 2.146a.5.5 0 0 0 .707.708l2.147-2.147 2.146 2.147a.5.5 0 0 0 .707-.708L9.39 8l2.146-2.146a.5.5 0 0 0-.707-.708L8.683 7.293 6.536 5.146a.5.5 0 0 0-.707 0z"/>
              <path d="M13.683 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-7.08a2 2 0 0 1-1.519-.698L.241 8.65a1 1 0 0 1 0-1.302L5.084 1.7A2 2 0 0 1 6.603 1h7.08zm-7.08 1a1 1 0 0 0-.76.35L1 8l4.844 5.65a1 1 0 0 0 .759.35h7.08a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1h-7.08z"/>
            </svg>
            戻る
          </a>
          <button class="btn btn-primary" type="submit" name="btn_send">日記生成</button>
        </div>
      </form>
    </div>
  </div>

</div>

<script type="text/javascript">
  $(".date-picker").datepicker({
    format: "yyyy-mm-dd",
    todayBtn: "linked",
    language: "ja",
  });
</script>

{% endblock %}

src/templates/gentext/generate_all.html
{% extends "_common/base.html" %}
{% block sub_title %}TOP{% endblock %}

{% block main %}

<div class="gentext-generate text-center">

  <div class="ui-heading">
    <h2>文章を生成します</h2>
  </div>

  <div class="mb-4">
    <div class="flex-fill">
      <form class="ui-form bg-white shadow rounded-3 p-5" method="POST" action="{% url 'gentext:result_all' %}">
        {% csrf_token %}

        <diV class="d-flex justfy-content-start mb-4">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="mode" value="range" id="mode_range" checked>
            <label class="form-check-label" for="mode_range">
              期間選択
            </label>
          </div>
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="mode" value="span" id="mode_span">
            <label class="form-check-label" for="mode_span">
              日数選択
            </label>
          </div>
        </diV>

        <div class="range-box">
          <div class="text-start">夏休みの期間指定</div>
          <div class="input-group input-daterange mt-2 mb-4">
            <input type="text" class="form-control text-start date-picker" name="diary_date_from">
            <div class="input-group-addon mx-2">to</div>
            <input type="text" class="form-control text-start date-picker" name="diary_date_to">
          </div>
        </div>

        <div class="span-box hidden">
          <div class="form-floating mb-4">
            <input class="form-control date-picker" type="text" name="diary_date" placeholder="date">
            <label>日記の日付</label>
          </div>
          <select name="span" class="form-select mb-4" aria-label="Default select">
            <option value="none" selected>作成する日数を選択してください</option>
            <option value="day">1日</option>
            <option value="week">1週間(7日)</option>
            <option value="month">1カ月(30日)</option>
          </select>
        </div>

        <div class="mt-1 d-flex justify-content-center">
          <a class="btn btn-secondary mx-1" href="{% url 'gentext:index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace" viewBox="0 0 16 16">
              <path d="M5.83 5.146a.5.5 0 0 0 0 .708L7.975 8l-2.147 2.146a.5.5 0 0 0 .707.708l2.147-2.147 2.146 2.147a.5.5 0 0 0 .707-.708L9.39 8l2.146-2.146a.5.5 0 0 0-.707-.708L8.683 7.293 6.536 5.146a.5.5 0 0 0-.707 0z"/>
              <path d="M13.683 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-7.08a2 2 0 0 1-1.519-.698L.241 8.65a1 1 0 0 1 0-1.302L5.084 1.7A2 2 0 0 1 6.603 1h7.08zm-7.08 1a1 1 0 0 0-.76.35L1 8l4.844 5.65a1 1 0 0 0 .759.35h7.08a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1h-7.08z"/>
            </svg>
            戻る
          </a>
          <button class="btn btn-primary" type="submit" name="btn_send">日記生成</button>
        </div>
      </form>
    </div>
  </div>

</div>

<script type="text/javascript">
  $(".date-picker").datepicker({
    format: "yyyy-mm-dd",
    todayBtn: "linked",
    language: "ja",
  });

  let mode = $("input[name='mode']");

  mode.change(function()
  {
    console.log($(this).val());
    if( $(this).val() == 'span' )
    {
      $('.range-box').addClass('hidden');
      $('.span-box').removeClass('hidden');
    }
    else if( $(this).val() == 'range' )
    {
      $('.span-box').addClass('hidden');
      $('.range-box').removeClass('hidden');
    }
  })
</script>

{% endblock %}

src/templates/gentext/index.html
{% extends "_common/base.html" %}
{% block sub_title %}TOP{% endblock %}

{% block main %}

<div id="canvas">
  <div id="diary-zoom">
    <div class="diary">
      {# タブ #}
      <div ignore="1" class="tabs">
        <div class="left"></div>
        <div class="right"></div>
      </div>

      {# 日記 #}
      <div class="hard cover"></div>
      <div class="hard"></div>

      <div class="generate d-flex align-items-center text-center">
        <a class="btn btn-primary" href="{% url 'gentext:generate' %}">新しい日記を書く</a>
        <a class="btn btn-outline-primary" href="{% url 'gentext:generate_all' %}">一気につくる</a>
      </div>

      {% for page in pages %}
      <div class="page">
        <div class="d-flex flex-column m-3 h-100">
          <div class="page-date text-end">{{ page.date }}</div>
          <div class="page-image h-50 text-center d-flex justify-content-center my-3 border">
            <img class="h-100" src="{{ page.img_path }}">
          </div>
          <div class="page-text">{{ page.body }}</div>
        </div>
      </div>
      {% empty %}
        <div class="page">
          <div class="h-100 w-100 text-center p-5">
            ページが見つかりませんでした。<br>
            新しい日記を書いてみましょう。
          </div>
        </div>
      {% endfor %}

      <div class="hard before-last"></div>
      <div class="hard last"></div>
    </div>
  </div>

  <div id="slider-bar" class="turnjs-slider">
    <div id="slider"></div>
  </div>
</div>


<script type="text/javascript">

let page_num = $(".diary .hard").length + $(".diary .page").length + 1;
let mode = "double";

if( (page_num % 2) != 0 )
{
  $(".before-last").before("<div class='page-wrapper'></div>");
  console.log($('.before-last').before())
  page_num++;
}

if($(window).width() < 1024)
{
  mode = "single";
  $(".diary").children(".hard").each(function(i, value)
  {
    value.remove(".hard");
  });
}

function loadApp()
{
  let diary = $(".diary");

  if( diary.width() == 0 || diary.height() == 0 )
  {
    setTimeout(loadApp, 10);
    return;
  }

  // マウスホイール

  $("#diary-zoom").mousewheel(function(event, delta, deltaX, deltaY)
  {
    let data = $(this).data();
    let step = page_num;
    let diary = $(".diary");
    let actualPos = $("#slider").slider("value") * step;

    if( typeof(data.scrollX) === "undefined" )
    {
      data.scrollX = actualPos;
      data.scrollPage = diary.turn("page");
    }

    data.scrollX = Math.min($("#slider").slider("option", "max") * step,
      Math.max(0, data.scrollX + deltaX));

    let actualView = Math.round(data.scrollX / step);
    let page = Math.min(diary.turn("pages"), Math.max(1, actualView*2 - 2));

    if( $.inArray(data.scrollPage, diary.turn("view", page)) == -1 )
    {
      data.scrollPage = page;
      diary.turn("page", page);
    }

    if (data.scrollTimer)
      clearInterval(data.scrollTimer);

    data.scrollTimer = setTimeout(function()
    {
      data.scrollX = undefined;
      data.scrollPage = undefined;
      data.scrollTimer = undefined;
    }, 1000);

  });

  // スライダー

  $("#slider").slider({
    min: 1,
    max: 100,

    start: function(event, ui) {
      if( !window._thumbPreview )
      {
        _thumbPreview = $("<div />", {"class": "thumbnail"}).html("<div></div>");
        setPreview(ui.value);
        _thumbPreview.appendTo($(ui.handle));
      }
      else
      {
        setPreview(ui.value);
      }

      moveBar(false);
    },

    slide: function(event, ui)
    {
      setPreview(ui.value);
    },

    stop: function()
    {
      if( window._thumbPreview )
        _thumbPreview.removeClass("show");

      $(".diary").turn("page", Math.max(1, $(this).slider("value") * 2 - 2));
    }
  });


  // URIs

  Hash.on("^page\/([0-9]*)$", {
    yep: function(path, parts)
    {
      var page = parts[1];

      if( page !== undefined )
      {
        if ($(".diary").turn("is"))
          $(".diary").turn("page", page);
      }

    },
    nop: function(path)
    {
      if( $(".diary").turn("is") )
      {
        $(".diary").turn("page", 1);
      }
    }
  });

  // Arrows

  $(document).keydown(function(e){
    let previous = 37;
    let next = 39;

    switch (e.keyCode)
    {
      case previous:
        $(".diary").turn("previous");
        break;

      case next:
        $(".diary").turn("next");
        break;
    }

  });

  // 日記

  diary.turn(
  {
    pages: page_num,
    elevation: 50,
    acceleration: false,
    gradients: true,
    autoCenter: true,
    duration: 1000,
    display: mode,
    when: {
    turning: function(e, page, view)
    {
      let diary = $(this);
      let currentPage = diary.turn("page");
      let pages = diary.turn("pages");

      if( currentPage > 3 && currentPage < pages - 3 )
      {
        if( page == 1 )
        {
          diary.turn("page", 2).turn("stop").turn("page", page);
          e.preventDefault();
          return;
        }
        else if( page == pages )
        {
          diary.turn("page", pages-1).turn("stop").turn("page", page);
          e.preventDefault();
          return;
        }
      }
      else if( page > 3 && page < pages - 3 )
      {
        if( currentPage == 1 )
        {
          diary.turn("page", 2).turn("stop").turn("page", page);
          e.preventDefault();
          return;
        }
        else if( currentPage == pages )
        {
          diary.turn("page", pages-1).turn("stop").turn("page", page);
          e.preventDefault();
          return;
        }
      }

      Hash.go("page/"+page).update();

      if( page == 1 || page == pages )
        $(".diary .tabs").hide();
    },

    turned: function(e, page, view)
    {
      let diary = $(this);

      $("#slider").slider("value", getViewNumber(diary, page));

      if( page != 1 && page != diary.turn("pages") )
        $(".diary .tabs").fadeIn(500);
      else
        $(".diary .tabs").hide();

      diary.turn("center");
      updateTabs();
    },

    start: function(e, pageObj)
    {
      moveBar(true);
    },

    end: function(e, pageObj)
    {
      let diary = $(this);

      setTimeout(function() {
        $("#slider").slider("value", getViewNumber(diary));
      }, 1);

      moveBar(false);
    },
  }
  }). turn("page", 2);


  $("#slider").slider("option", "max", numberOfViews(diary));

  diary.addClass("animated");


  // キャンバスを表示

  $("#canvas").css({visibility: "visible"});
}

// キャンバスを非表示

$("#canvas").css({visibility: "hidden"});


// yepnope.jsによる読み込み

yepnope({
  test: Modernizr.csstransforms,
  yep: ["/static/js/turn-js/lib/turn.min.js", "/static/css/turn-js/jquery.ui.css"],
  nope: ["/static/js/turn-js/lib/turn.html4.min.js", "/static/css/turn-js/jquery.ui.html4.css"],
  both: ["/static/css/turn-js/diary.css", "/static/js/turn-js/diary.js"],
  complete: loadApp
});

$(window).resize(function()
{
  location.reload();
});

</script>
{% endblock %}

src/templates/gentext/result_all.html
{% extends "_common/base.html" %}
{% block sub_title %}TOP{% endblock %}

{% block main %}

<div class="gentext-select text-center">

  <div class="ui-heading">
    {% if results == 'wait' %}
      <h2>日記生成中...</h2>
    {% else %}
      <h2>お気に入りを選択</h2>
    {% endif %}
  </div>

  <div class="mb-4">
    <div class="bg-white shadow rounded-3 p-5">
      {% if results == 'wait' %}
        {# ローディングアニメーション #}
        <div class="d-flex justify-content-center">
          <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      {% else %}
        {# 結果の表示 #}
        <form class="text-start" method="POST" action="">
          {% csrf_token %}
          <table>
            {% for result in results %}
              <tr>
                <td>{{ result.date }}</td>
                <td>{{ result.text }}</td>
              </tr>
            {% endfor %}
          </table>

          <div class="text-center mt-3">
            <button type="submit" class="btn opacity-25 btn-outline-primary" name="btn_next">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
              </svg>
              保存
            </button>
          </div>
        </form>
      {% endif %}
    </div>
  </div>

  <div class="mt-1 d-flex justify-content-center">
    <a class="btn btn-secondary mx-1" href="{% url 'gentext:generate_all' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace" viewBox="0 0 16 16">
        <path d="M5.83 5.146a.5.5 0 0 0 0 .708L7.975 8l-2.147 2.146a.5.5 0 0 0 .707.708l2.147-2.147 2.146 2.147a.5.5 0 0 0 .707-.708L9.39 8l2.146-2.146a.5.5 0 0 0-.707-.708L8.683 7.293 6.536 5.146a.5.5 0 0 0-.707 0z"/>
        <path d="M13.683 1a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-7.08a2 2 0 0 1-1.519-.698L.241 8.65a1 1 0 0 1 0-1.302L5.084 1.7A2 2 0 0 1 6.603 1h7.08zm-7.08 1a1 1 0 0 0-.76.35L1 8l4.844 5.65a1 1 0 0 0 .759.35h7.08a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1h-7.08z"/>
      </svg>
      戻る
    </a>
  </div>

</div>


{# 結果が取得されるまでは5秒ごとに画面をリロード #}
<script type="text/javascript">
  {% if results == 'wait' %}
  setTimeout(() => {
      location.reload();
  }, 3000);
  {% endif %}
</script>

{% endblock %}