src/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('signup/', views.signup, name='signup'),
	path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_reset'),
	path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_done'),
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("top.urls")),
    path('accounts/', include("accounts.urls")),
    path('gentext/', include("gentext.urls")),
    path('corpus/', include("corpus.urls")),
]

src/gentext/urls.py
from django.urls import path
from . import views

app_name = 'gentext'
urlpatterns = [
	path('', views.index, name='index'),
	path('generate/', views.generate, name='generate'),
	path('generate_all/', views.generate_all, name='generate_all'),
	path('select/', views.select, name='select'),
	path('result_all/', views.result_all, name='result_all'),
]

src/top/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name="index"),
]

src/top/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
	params = {}
	return render(request, 'top/index.html', params)

src/templates/top/index.html
{% extends "_common/base.html" %}
{% block sub_title %}TOP{% endblock %}

{% block main %}
<div class="top-index h-75">

  <div class="top-visual d-flex flex-column h-100 mx-5">
    <div class="container text-center flex-fill position-relative">
      <h1 id="app-title" class="block position-absolute top-50 start-50 translate-middle w-100">Reptiles 夏休み日記</h1>
    </div>

    <div class="container text-center mb-5">
      {% if request.user.is_anonymous %}
        <a class="btn-top btn btn-outline-primary btn-lg fw-bold bg-white" href="{% url 'accounts:login' %}">ログイン/新規登録</a>
      {% else %}
        <a class="btn-top btn btn-outline-primary btn-lg fw-bold bg-white" href="{% url 'gentext:index' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-vector-pen" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M10.646.646a.5.5 0 0 1 .708 0l4 4a.5.5 0 0 1 0 .708l-1.902 1.902-.829 3.313a1.5 1.5 0 0 1-1.024 1.073L1.254 14.746 4.358 4.4A1.5 1.5 0 0 1 5.43 3.377l3.313-.828L10.646.646zm-1.8 2.908-3.173.793a.5.5 0 0 0-.358.342l-2.57 8.565 8.567-2.57a.5.5 0 0 0 .34-.357l.794-3.174-3.6-3.6z"/>
            <path fill-rule="evenodd" d="M2.832 13.228 8 9a1 1 0 1 0-1-1l-4.228 5.168-.026.086.086-.026z"/>
          </svg>
          日記を開く
        </a>
      {% endif %}
    </div>
  </div>

</div>

{# 画面下部のパネル #}
<div class="pt-4 h-25 w-100 d-flex flex-column justify-content-center align-center text-center">
</div>

{% endblock %}